### ISSUE TITLE
Tell me how the downloading process works?

### ISSUE THREAD

**Issue by saifsmailbox98** [xtream1101/scrape-itebooks#2]
Hey, I have set the code on cron, but I see only folders getting created with a pdf and an image of the ebooks, but they are corrupt. Are these dummy files, like first the script will create dummy file of all the pdfs and then download it or the download will start after one section is done. Tell me the process.

**Comment by saifsmailbox98** [comment]
Also, some folder have pdfs smaller than jpgs. Both are not opening with there correct programs. But both files are interchanged with respect to there file format. The jpg opens in adobe reader and the pdf is actually an image. Also most of the folders have files of the order of some KBs.

**Comment by xtream1101** [comment]
I have no idea how that bug was here for so long. Thanks for seeing this. Some of the ebooks are just small/low quality, nothing I can do about that.

**Comment by saifsmailbox98** [comment]
Yeah, its a big bug. You better fix it. You have a very good script. Maybe it-ebooks changed something on their website and thats causing the problem. I don't know. Is the other script working? The one with the json file. I tried it but got some errors similar to these https://github.com/xtream1101/it-ebooks-dl/issues/2. Also is the json one going to download all the files from beginning if my computer restarts in between the process, also can I put it on cron?

**Comment by xtream1101** [comment]
I already pushed a fix the this bug. Just need to delete the database file and the books it downloaded. Do a `git pull` and run it again.

If you stop the script and run it again, it will start where it left off. Adding this to a cron job is what this was designed for.

**Comment by saifsmailbox98** [comment]
Ok, what about some ebooks being downloaded with small file size?

**Comment by xtream1101** [comment]
They might just be that small/low quality. This script gets what ever they have uploaded so I have no control over that.

**Comment by saifsmailbox98** [comment]
Okay. Thanks.

**Comment by saifsmailbox98** [comment]
Okay, thanks. :smile:
