### ISSUE TITLE
IncompleteRead exceptions

### ISSUE THREAD

**Issue by garyng** [xtream1101/scrape-itebooks#3]
![image](https://cloud.githubusercontent.com/assets/4453664/14061717/0fac338c-f3c2-11e5-95dc-c05949522e68.png)

Occurs very frequently.. Any fixes?
Running Python 3.5.1 on Windows 10 x64

PS : Consider showing a progress bar while downloading? :smile:

**Comment by garyng** [comment]
I wrote a C# implementation of this scrapper :smile: :smile: 

https://github.com/garyng/gITEBooksGrabber

**Comment by xtream1101** [comment]
Refactored the code base. All previous versions will not be compatible. If this happens with the new code I will be sure to fix this.
