### ISSUE TITLE
No module named 'custom_utils.custom_utils'

### ISSUE THREAD

**Issue by flotteur** [xtream1101/scrape-itebooks#5]
# Hi,

I'm trying to get the script running but i'm having an issue with the imports: 

`> python main.py -d ./all`

> Traceback (most recent call last):
>   File "main.py", line 7, in <module>
>     from custom_utils.custom_utils import CustomUtils
> ImportError: No module named 'custom_utils.custom_utils'

I'm running python 3.5.2 on windows 10 x64 with the following packages installed:
- beautifulsoup4 (4.5.1)
- custom-utils (1.0.0)
- hashids (1.1.0)
- Pillow (3.3.1)
- pip (8.1.2)
- psycopg2 (2.6.2)
- pytz (2016.6.1)
- PyYAML (3.11)
- requests (2.11.1)
- setuptools (20.10.1)
- SQLAlchemy (1.1.0b3)

I a complete beginner in python, any idea what is going on?

Thanks!

**Comment by xtream1101** [comment]
the package `custom_utils` was linked to in the readme, had to be downloaded and install from the repo. This is irrelevant now, the current `master` branch has been refactored.

**Comment by flotteur** [comment]
Thank you!
