### ISSUE TITLE
scrape-lib not available

### ISSUE THREAD

**Issue by knowledgewarrior** [xtream1101/scrape-itebooks#9]
Get the following error:

pip3 install -r requirements.txt 
Obtaining scraper_lib from git+https://git.eddyhintze.com/xtream1101/scraper-lib@master#egg=scraper_lib (from -r requirements.txt (line 1))
  Cloning https://git.eddyhintze.com/xtream1101/scraper-lib (to master) to ./src/scraper-lib
Username for 'https://git.eddyhintze.com': 
Password for 'https://git.eddyhintze.com': 
remote: invalid token
fatal: Authentication failed for 'https://git.eddyhintze.com/xtream1101/scraper-lib/'
Command "git clone -q https://git.eddyhintze.com/xtream1101/scraper-lib /home/jmf/src/scrape-itebooks/src/scraper-lib" failed with error code 128 in None

**Comment by knowledgewarrior** [comment]
resolved by changing requirements.txt to:

-e git+https://github.com/xtream1101/scraper-lib@master#egg=scraper_lib
-e git+https://github.com/xtream1101/scraper-monitor-lib@master#egg=scraper_monitor
cutil
sqlalchemy

**Comment by xtream1101** [comment]
I have not kept this repo up to date because the site no longer has download links. If they ever go back up I will update this scraper.
